// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"
const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onDistanceChange();
void onTriggeredChange();
void onMaxThresholdChange();
void onMinThresholdChange();

float distance;
bool triggered;

float max_threshold;
float min_threshold;
void initProperties(){

  ArduinoCloud.addProperty(distance, READWRITE, ON_CHANGE, onDistanceChange);
  ArduinoCloud.addProperty(triggered,READWRITE, ON_CHANGE , onTriggeredChange);
  ArduinoCloud.addProperty(max_threshold, READWRITE, ON_CHANGE, onMaxThresholdChange);
  ArduinoCloud.addProperty(distance, READWRITE, ON_CHANGE, onMinThresholdChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);